server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloud2020?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
  zipkin:
    base-url: localhost:9411      #zipkin-server的地址
  sleuth:
    sampler:
      #设置采样率，取值在0~1之间，1代表全部采集
      probability: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka,http://eureka7002:7002/eureka  #使用Eureka集群
      defaultZone: http://eureka7003:7003/eureka #使用单机版Eureka
  instance:
    instance-id: payment8001  #在Eureka显示服务时不显示主机名，而是显示这个配置
    prefer-ip-address: true  #鼠标指向服务时，左下角显示该服务的ip
    #超时剔除服务
    lease-expiration-duration-in-seconds: 2
    #客户端向Eureka发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ccb.springcloud.entities


