server:
  port: 80
spring:
  application:
    name: cloud-consumer-order-feign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7003:7003/eureka #使用单机版Eureka
