server:
  port: 9527
spring:
  application:
    name: cloud-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: payment_routes #路由的ID，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/** #断言，路径匹配的进行路由
#        - id: payment_route2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka,http://eureka7002:7002/eureka  #使用Eureka集群
      defaultZone: http://eureka7003:7003/eureka #使用单机版Eureka