server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routes #路由的ID，没有固定的规则，但是要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #动态路由，到eureka中获取微服务名为cloud-payment-service的服务，并实现负载均衡
          predicates:
            - Path=/payment/get/** #断言，路径匹配的进行路由
        - id: payment_route2
#          uri: http://localhost:8001  #静态路由，这样配置就写死了，难以扩展
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka,http://eureka7002:7002/eureka  #使用Eureka集群
      defaultZone: http://eureka7003:7003/eureka #使用单机版Eureka