server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002
  client:
    #false自己就是注册中心，不用注册自己
    register-with-eureka: false
    #false因为本身就是注册中心，不需要再向注册中心获取其他服务的地址
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka