server:
  port: 80  #由于提供给外部访问的系统基本不会通过端口来访问的，而是使用默认端口80进行访问的，其实用nginx搭建服务器集群也是这样
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001:7001/eureka,http://eureka7003:7003/eureka,http://eureka7002:7002/eureka
      defaultZone: http://eureka7003:7003/eureka #使用单机版Eureka
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: localhost:9411      #zipkin-server的地址
  sleuth:
    sampler:
      #设置采样率，取值在0~1之间，1代表全部采集
      probability: 1